#!/usr/bin/env bash
\cp -rf ./experiments/5bins-mC/results/Theta.MutSel.all.stacked.pdf ./manuscript/artworks/stacked.allSNPs.pdf
\cp -rf ./experiments/5bins-mC/results/Theta.MutSel.pos-weak.stacked.pdf ./manuscript/artworks/stacked.weak-pos-SNPs.pdf
\cp -rf ./experiments/5bins-mC/results/Theta.MutSel.neg-weak.stacked.pdf ./manuscript/artworks/stacked.weak-neg-SNPs.pdf
\cp -rf ./experiments/5bins-mC/results/Theta.MutSel.P-Seq0.heatmap.pdf ./manuscript/artworks/heatmap.neutral.pdf
\cp -rf ./experiments/5bins-mC/results/Theta.MutSel.P-Sinf0.heatmap.pdf ./manuscript/artworks/heatmap.neg.pdf
\cp -rf ./experiments/5bins-mC/results/Theta.MutSel.P-Ssup0.heatmap.pdf ./manuscript/artworks/heatmap.pos.pdf
\cp -rf ./experiments/5bins-mC/analysis/Homo_sapiens.AFR.MutSel-sfs.normalize.pdf ./manuscript/artworks/AFR.SFS.pdf
\cp -rf ./experiments/5bins-mC/analysis/Homo_sapiens.AFR.MutSel.polyDFE_C.pdf ./manuscript/artworks/AFR.polyDFE.pdf
\cp -rf ./data_processed/opportunities_bins5Mask0.9/DFE.Homo_sapiens.AFR.MutSel.pdf ./manuscript/artworks/AFR.histogramDFE.pdf
\cp -rf ./data_processed/vcf_annotate_bins5Mask0.9/snps.Homo_sapiens.AFR.MutSel.histogram.pdf ./manuscript/artworks/AFR.histogramSNP.pdf
\cp -rf ./data_processed/vcf_annotate_bins5Mask0.9/snps.Homo_sapiens.AFR.MutSel.histogram.full.pdf ./manuscript/artworks/AFR.histogramSNP.full.pdf
\cp -rf ./data_processed/ancestral_bins5Mask0.9/Homo_sapiens.AFR.pdf ./manuscript/artworks/AFR.histogramDiv.pdf
\cp -rf ./experiments/5bins-mC/regression-MutSel/results.watterson.all_P-Ssup0.scatter.pdf  ./manuscript/artworks/scatter.watterson.allSNPs.P-Ssup0.pdf
\cp -rf ./experiments/5bins-mC/regression-MutSel/results.watterson.all_P-Sinf0.scatter.pdf  ./manuscript/artworks/scatter.watterson.allSNPs.P-Sinf0.pdf
\cp -rf ./experiments/5bins-mC/regression-MutSel/results.watterson.all_P-Seq0.scatter.pdf  ./manuscript/artworks/scatter.watterson.allSNPs.P-Seq0.pdf
\cp -rf ./experiments/5bins-mC/regression-MutSel/results.watterson.bayes_P-Ssup0_P-pos.scatter.pdf ./manuscript/artworks/scatter.watterson.Bayes.pdf
\cp -rf ./experiments/2bins-mC/regression-MutSel/results.watterson.ratio_neg_P-Ssup0.scatter.pdf ./manuscript/artworks/scatter.watterson.R_p+.pdf
\cp -rf ./experiments/2bins-mC/regression-MutSel/results.watterson.ratio_neg_omega_div.scatter.pdf ./manuscript/artworks/scatter.watterson.R_div.pdf
\cp -rf ./data_processed/opportunities_bins2Mask0.9/DFE.Homo_sapiens.AFR.MutSel.pdf ./manuscript/artworks/2bins.AFR.histogramDFE.pdf
\cp -rf ./experiments/3bins-mC/results/Theta.MutSel.all.stacked.pdf ./manuscript/artworks/3bins.stacked.allSNPs.pdf
\cp -rf ./experiments/3bins-mC/analysis/Homo_sapiens.AFR.MutSel.polyDFE_C.pdf ./manuscript/artworks/3bins.AFR.polyDFE.pdf
\cp -rf ./data_processed/opportunities_bins3Mask0.9/DFE.Homo_sapiens.AFR.MutSel.pdf ./manuscript/artworks/3bins.AFR.histogramDFE.pdf
\cp -rf ./data_processed/vcf_annotate_bins3Mask0.9/snps.Homo_sapiens.AFR.MutSel.histogram.pdf ./manuscript/artworks/3bins.AFR.histogramSNP.pdf
\cp -rf ./data_processed/experimental_DFE.pdf ./manuscript/artworks/2bins.Yeast.experimentalDFE.pdf
\cp -rf ./data_processed/population_DFE.pdf ./manuscript/artworks/2bins.AFR.populationDFE.pdf