#!/usr/bin/env bash
\cp -rf ./experiments/3bins-mC-nodiv/analysis/Homo_sapiens.AFR.MutSel-sfs.pdf ./manuscript/artworks/AFR.SFS.pdf
\cp -rf ./experiments/3bins-mC-nodiv/analysis/Homo_sapiens.AFR.MutSel-sfs.normalize.pdf ./manuscript/artworks/AFR.SFS.normalize.pdf
\cp -rf ./experiments/3bins-mC-nodiv/analysis/Homo_sapiens.AFR.MutSel.polyDFE_C.pdf ./manuscript/artworks/AFR.polyDFE.pdf
\cp -rf ./data_processed/opportunities_bins3Mask0.9/DFE.Homo_sapiens.AFR.MutSel.pdf ./manuscript/artworks/AFR.histogramDFE.pdf
\cp -rf ./data_processed/ancestral_bins3Mask0.9/Homo_sapiens.AFR.pdf ./manuscript/artworks/AFR.histogramDiv.pdf
\cp -rf ./supp/hist/subs.Homo_sapiens.AFR.bins3Mask0.9.folded_ratio.pdf ./manuscript/artworks/subs.Homo_sapiens.AFR.folded_ratio.pdf
\cp -rf ./supp/hist/poly.Homo_sapiens.AFR.bins3Mask0.9.folded_ratio.pdf ./manuscript/artworks/poly.Homo_sapiens.AFR.folded_ratio.pdf
\cp -rf ./experiments/3bins-mC-nodiv/regression-MutSel/results.pop_size.bayes_P-Spos_P-pos.scatter.pdf ./manuscript/artworks/results.pop_size.Bayes.pdf
\cp -rf ./experiments/3bins-mC-nodiv/regression-MutSel/results.pop_size.mut_sum_P-Sweak.scatter.pdf ./manuscript/artworks/results.pop_size.all_P-Sweak.scatter.pdf
\cp -rf ./experiments/3bins-mC-nodiv/regression-MutSel/results.pop_size.weak_P-Sweak.scatter.pdf ./manuscript/artworks/results.pop_size.weak_P-Sweak.scatter.pdf
\cp -rf ./experiments/3bins-mC-nodiv/regression-MutSel/results.pop_size.mut_sum_P-Sneg.scatter.pdf ./manuscript/artworks/results.pop_size.all_P-Sneg.scatter.pdf
\cp -rf ./experiments/3bins-mC-nodiv/regression-MutSel/results.pop_size.neg_P-Sneg.scatter.pdf ./manuscript/artworks/results.pop_size.neg_P-Sneg.scatter.pdf
\cp -rf ./experiments/3bins-mC-nodiv/regression-MutSel/results.pop_size.mut_sum_P-Spos.scatter.pdf ./manuscript/artworks/results.pop_size.all_P-Spos.scatter.pdf
\cp -rf ./experiments/3bins-mC-nodiv/regression-MutSel/results.pop_size.pos_P-Spos.scatter.pdf ./manuscript/artworks/results.pop_size.pos_P-Spos.scatter.pdf
\cp -rf ./experiments/3bins-mC-nodiv/results/Theta.MutSel.weak.stacked.pdf ./manuscript/artworks/Theta.weak.stacked.pdf
\cp -rf ./experiments/3bins-mC-nodiv/results/Theta.MutSel.neg.stacked.pdf ./manuscript/artworks/Theta.neg.stacked.pdf
\cp -rf ./experiments/3bins-mC-nodiv/results/Theta.MutSel.pos.stacked.pdf ./manuscript/artworks/Theta.pos.stacked.pdf
\cp -rf ./experiments/3bins-mC-nodiv/regression-MutSel/results.distance.recall_pos.scatter.pdf ./manuscript/artworks/results.distance.recall_pos.scatter.pdf
\cp -rf ./experiments/3bins-mC/regression-MutSel/results.distance.recall_pos.scatter.pdf ./manuscript/artworks/results.distance.recall_pos.div.scatter.pdf
\cp -rf ./data_processed/upset_plot/bins3Mask0.9.pdf ./manuscript/artworks/UpSet_plot.pdf
\cp -rf ./data_processed/trimmed_tree_sample_all.tsv.tree ./manuscript/artworks/PGLM.tree
\cp -rf ./data_processed/opportunities_bins3Mask0.9/DFE.Chlorocebus_sabaeus.Saint_Kitts.MutSel.pdf ./manuscript/artworks/DFE.Chlorocebus_sabaeus.Saint_Kitts.MutSel.pdf
\cp -rf ./data_processed/opportunities_bins3Mask0.9/DFE.Chlorocebus_sabaeus.Saint_Kitts.MutSel.Flow.pdf ./manuscript/artworks/DFE.Chlorocebus_sabaeus.Saint_Kitts.MutSel.Flow.pdf
\cp -rf ./supp/hist/subs.Chlorocebus_sabaeus.Saint_Kitts.bins3Mask0.9.pdf ./manuscript/artworks/subs.Chlorocebus_sabaeus.Saint_Kitts.bins3Mask0.9.pdf
\cp -rf ./supp/hist/poly.Chlorocebus_sabaeus.Saint_Kitts.bins3Mask0.9.pdf ./manuscript/artworks/poly.Chlorocebus_sabaeus.Saint_Kitts.bins3Mask0.9.pdf
\cp -rf ./experiments/3bins-mC-nodiv/analysis/Chlorocebus_sabaeus.Saint_Kitts.MutSel-sfs.normalize.pdf ./manuscript/artworks/Chlorocebus_sabaeus.Saint_Kitts.MutSel-sfs.normalize.pdf
\cp -rf ./experiments/3bins-mC-nodiv/analysis/Chlorocebus_sabaeus.Saint_Kitts.MutSel.polyDFE_C.pdf ./manuscript/artworks/Chlorocebus_sabaeus.Saint_Kitts.MutSel.polyDFE_C.pdf
\cp -rf ./experiments/3bins-mC-nodiv-CpG/analysis/Chlorocebus_sabaeus.South_Africa.MutSel-sfs.pdf ./manuscript/artworks/CpG.Chlorocebus_sabaeus.South_Africa.MutSel-sfs.pdf
\cp -rf ./experiments/3bins-mC-nodiv-CpG/analysis/Chlorocebus_sabaeus.South_Africa.MutSel.polyDFE_C.pdf ./manuscript/artworks/CpG.Chlorocebus_sabaeus.South_Africa.MutSel.polyDFE_C.pdf
\cp -rf ./experiments/3bins-mC-nodiv-CpG/analysis/Homo_sapiens.AFR.MutSel-sfs.pdf ./manuscript/artworks/CpG.Homo_sapiens.AFR.MutSel-sfs.pdf
\cp -rf ./experiments/3bins-mC-nodiv-CpG/analysis/Homo_sapiens.AFR.MutSel.polyDFE_C.pdf ./manuscript/artworks/CpG.Homo_sapiens.AFR.MutSel.polyDFE_C.pdf
\cp -rf ./supp/ontology_poly/Homo_sapiens.EUR.hist_pval.pdf ./manuscript/artworks/ontology_poly.Homo_sapiens.EUR.hist.pdf
\cp -rf ./supp/ontology_poly/Homo_sapiens.EUR.tex ./manuscript/artworks/ontology_poly.Homo_sapiens.EUR.tex