#!/usr/bin/env bash
\cp -rf ./experiments/50windows-polyDFE-mC-non-adaptive/regression/results.watterson.a.scatter.pdf ./manuscript/artworks/scatter.watterson.slopeSpopSphy.pdf
\cp -rf ./experiments/50windows-polyDFE-mC-non-adaptive/results/regression.MutSel.SelCoeff.scatter.pdf ./manuscript/artworks/scatter.Sphy.Spop.pdf
\cp -rf ./experiments/3bins-polyDFE-mC/results/Theta.MutSel.weak.stacked.pdf ./manuscript/artworks/stacked.weakSNPs.pdf
\cp -rf ./experiments/5bins-polyDFE-mC/results/Theta.MutSel.all.stacked.pdf ./manuscript/artworks/stacked.allSNPs.pdf
\cp -rf ./experiments/5bins-polyDFE-mC/results/Theta.MutSel.pos-weak.stacked.pdf ./manuscript/artworks/stacked.weak-pos-SNPs.pdf
\cp -rf ./experiments/5bins-polyDFE-mC/results/Theta.MutSel.neg-weak.stacked.pdf ./manuscript/artworks/stacked.weak-neg-SNPs.pdf
\cp -rf ./experiments/5bins-polyDFE-mC/results/Theta.MutSel.P-Seq0.heatmap.pdf ./manuscript/artworks/heatmap.neutral.pdf
\cp -rf ./experiments/5bins-polyDFE-mC/results/Theta.MutSel.P-Sinf0.heatmap.pdf ./manuscript/artworks/heatmap.neg.pdf
\cp -rf ./experiments/5bins-polyDFE-mC/results/Theta.MutSel.P-Ssup0.heatmap.pdf ./manuscript/artworks/heatmap.pos.pdf
\cp -rf ./experiments/5bins-polyDFE-mC/analysis/Homo_sapiens.AFR.MutSel-sfs.normalize.pdf ./manuscript/artworks/AFR.SFS.pdf
\cp -rf ./experiments/5bins-polyDFE-mC/analysis/Homo_sapiens.AFR.MutSel.polyDFE_C.pdf ./manuscript/artworks/AFR.polyDFE.pdf
\cp -rf ./data_processed/opportunities_bins5/DFE.Homo_sapiens.AFR.MutSel.pdf ./manuscript/artworks/AFR.histogramDFE.pdf
\cp -rf ./data_processed/vcf_annotate_bins5/snps.Homo_sapiens.AFR.MutSel.histogram.pdf ./manuscript/artworks/AFR.histogramSNP.pdf
\cp -rf ./data_processed/vcf_annotate_bins5/snps.Homo_sapiens.AFR.MutSel.histogram.full.pdf ./manuscript/artworks/AFR.histogramSNP.full.pdf
\cp -rf ./data_processed/ancestral_bins5/Homo_sapiens.AFR.pdf ./manuscript/artworks/AFR.histogramDiv.pdf
\cp -rf ./experiments/5bins-polyDFE-mC/regression-MutSel/results.watterson.all_P-Ssup0.scatter.pdf  ./manuscript/artworks/scatter.watterson.allSNPs.P-Ssup0.pdf
\cp -rf ./experiments/5bins-polyDFE-mC/regression-MutSel/results.watterson.all_P-Sinf0.scatter.pdf  ./manuscript/artworks/scatter.watterson.allSNPs.P-Sinf0.pdf
\cp -rf ./experiments/5bins-polyDFE-mC/regression-MutSel/results.watterson.all_P-Seq0.scatter.pdf  ./manuscript/artworks/scatter.watterson.allSNPs.P-Seq0.pdf
\cp -rf ./experiments/2bins-polyDFE-mC/regression-MutSel/results.watterson.ratio_neg_P-Ssup0.scatter.pdf ./manuscript/artworks/scatter.watterson.R_p+.pdf
\cp -rf ./experiments/2bins-polyDFE-mC/regression-MutSel/results.watterson.ratio_neg_omega_div.scatter.pdf ./manuscript/artworks/scatter.watterson.R_div.pdf
