experiment: "5cat-polyDFE-mC-SIFT"
SAMPLE_LIST: "sample_all.tsv"
subsample: 16
nbr_replicates: 12
bins: 0 # bins: 0 to classify based on sel_coeff or sift_score
METHOD_LIST: [ "MutSel", "SIFT", "Omega" ] # [ "MutSel", "Omega", "SW", "WS", "SIFT" ]
MODEL: "polyDFE_C" # [ "grapes", "polyDFE_D", "polyDFE_C" ]