experiment: "3bins-mC-CpG"
SAMPLE_LIST: "sample_all.tsv"
subsample: 16
nbr_replicates: 12
subsample_genes: -1
subsample_genes_ancestral: -1
bins: 3 # The number of bins: 0, 2, 3 or 5 for predetermined bins. Otherwise, bins with equal number of SNPs in each bin.
windows: 0 # The number of SNPs for each bin in the sliding windows, 0 if not sliding windows
mask_adaptation: false # Mask the sites with omega > omega_0
mask_CpG: true # Mask the CpG sites
mask_identity: 0.90 # Mask the sites with identity < mask_identity
mask_anc_proba_SNPS: 0.99 # Mask the SNPs with ancestral reconstruction probability (given by est-sfs) < mask_anc_proba_SNPS
mask_unaligned_flanks: 0 # Mask the sites for which the flanked regions are not aligned with the neighboring species (flanks of length mask_unaligned_flanks on each side, 0 to disable)
METHOD_LIST: [ "MutSel" ]
MODEL: "polyDFE_C"
ALPHA: true # If true, the Î± parameter is computed (requires to map substitutions in the terminal branch).
USE_DIVERGENCE: true # If true, the model use divergence (requires ALPHA to be true).
