experiment: "5cat-polyDFE-mC"
SAMPLE_LIST: "sample_test.tsv"
subsample: 16
nbr_replicates: 12
subsample_genes: 500
bins: 30 # bins: 0 to classify based on predetermined bins
METHOD_LIST: [ "MutSel", "SIFT", "Omega" ] # [ "MutSel", "Omega", "SIFT" ]
MODEL: "polyDFE_C" # [ "polyDFE_D", "polyDFE_C" ]