experiment: "100windows-polyDFE-mC-non-adaptive"
SAMPLE_LIST: "sample_all.tsv"
subsample: 16
nbr_replicates: 12
subsample_genes: 100
bins: 100 # bins: 0 to classify based on predetermined bins
windows: 5000 # True for sliding windows, 0 for bins
mask_adaptation: true
METHOD_LIST: [ "MutSel" ]
MODEL: "polyDFE_C"