experiment: "3bins-mC"
SAMPLE_LIST: "sample_all.tsv"
subsample: 16
nbr_replicates: 12
subsample_genes: -1
subsample_genes_ancestral: -1
bins: 3 # The number of bins: 0, 2, 3 or 5 for predetermined bins. Otherwise, bins with equal number of SNPs in each bin.
windows: 0 # The number of SNPs for each bin in the sliding windows, 0 if not sliding windows
mask_adaptation: false # Mask the sites with omega > omega_0
mask_CpG: false # Mask the CpG sites
mask_identity: 0.95 # Mask the sites with identity < mask_identity
METHOD_LIST: [ "MutSel" ]
MODEL: "polyDFE_C"
ALPHA: true # If true, the Î± parameter is computed (requires to map substitutions in the terminal branch).
USE_DIVERGENCE: true # If true, the model use divergence (requires ALPHA to be true).